version: '3'
services:
  php-apache:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ezpass123
      MYSQL_DATABASE: htalk
      MYSQL_USER: htalk
      MYSQL_PASSWORD: htalk
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql